export const Topics = [
  { label: 'Account', value: 'account' },
  { label: 'Projects', value: 'projects' },
  { label: 'Teams', value: 'teams' },
  { label: 'AI', value: 'ai' },
  { label: 'Analytics', value: 'analytics' },
  { label: 'API', value: 'api' },
  { label: 'CLI', value: 'cli' },
  { label: 'Build', value: 'build' },
  { label: 'Deployment', value: 'deployment' },
  { label: 'Git', value: 'git' },
  { label: 'Databases', value: 'databases' },
  { label: 'CMS', value: 'cms' },
  { label: 'Domains', value: 'domains' },
  { label: 'DNS', value: 'dns' },
  { label: 'Edge Middleware', value: 'middleware' },
  { label: 'Edge Network', value: 'edge-network' },
  { label: 'Caching', value: 'caching' },
  { label: 'Environment Variables', value: 'environment' },
  { label: 'Frameworks', value: 'frameworks' },
  { label: 'Functions', value: 'functions' },
  { label: 'Integrations', value: 'integrations' },
  { label: 'Logs', value: 'logs' },
  { label: 'Limits', value: 'limits' },
  { label: 'Usage', value: 'usage' },
  { label: 'Pricing', value: 'pricing' },
  { label: 'Observability', value: 'observability' },
  { label: 'OG Image Generation', value: 'og-image-generation' },
  { label: 'Policy', value: 'policy' },
  { label: 'Security', value: 'security' },
  { label: 'Runtimes', value: 'runtimes' },
  { label: 'Streaming', value: 'streaming' },
]
